//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hashashins_CRM.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminTablosu
    {
        public int Admin_ID { get; set; }
        public string Kullanici_Adi { get; set; }
        public string Sifre { get; set; }
    }
}
