//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hashashins_CRM.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmalarTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FirmalarTablosu()
        {
            this.CagrilarTablosu = new HashSet<CagrilarTablosu>();
        }
    
        public int Firma_ID { get; set; }
        public string Firma_Adi { get; set; }
        public string Yetkili_Adi { get; set; }
        public string Telefon_No { get; set; }
        public string Mail_Adresi { get; set; }
        public string Firma_İl { get; set; }
        public string Firma_İlce { get; set; }
        public string Firma_Adresi { get; set; }
        public string Sifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CagrilarTablosu> CagrilarTablosu { get; set; }
    }
}
