//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hashashins_CRM_Web.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GorevDetaylariTablosu
    {
        public int GorevDetaylar_ID { get; set; }
        public Nullable<int> Gorev { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Saat { get; set; }
    
        public virtual GorevlerTablosu GorevlerTablosu { get; set; }
    }
}
