//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hashashins_CRM_Web.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HashashinsDbEntities : DbContext
    {
        public HashashinsDbEntities()
            : base("name=HashashinsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTablosu> AdminTablosu { get; set; }
        public virtual DbSet<CagrilarTablosu> CagrilarTablosu { get; set; }
        public virtual DbSet<DepartmanlarTablosu> DepartmanlarTablosu { get; set; }
        public virtual DbSet<FirmalarTablosu> FirmalarTablosu { get; set; }
        public virtual DbSet<GorevDetaylariTablosu> GorevDetaylariTablosu { get; set; }
        public virtual DbSet<GorevlerTablosu> GorevlerTablosu { get; set; }
        public virtual DbSet<PersonelTablosu> PersonelTablosu { get; set; }
        public virtual DbSet<CagriDetaylariTablosu> CagriDetaylariTablosu { get; set; }
    }
}
